kind: ReplicaSet                                    
apiVersion: apps/v1                            
metadata:
  name: pod1
spec:
  replicas: 3  
  selector:                  
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [yadav, ydv, yadv]}
      - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: testpod7
      labels:              
        myname: yadav
    spec:
     containers:
       - name: con1
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
